- id: '1727616435677'
  alias: air-the-living-room
  description: Air out the living room
  trigger:
  - type: value
    platform: device
    device_id: 7f8557c6298a986c45086392c29693dd
    entity_id: sensor.awair_element_74845_score
    domain: sensor
    below: 70
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - type: carbon_dioxide
    platform: device
    device_id: 7f8557c6298a986c45086392c29693dd
    entity_id: sensor.awair_element_74845_carbon_dioxide
    domain: sensor
    above: 1200
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Abre la ventana
  mode: single
- id: '1727616809953'
  alias: desk-standup-afternoon
  description: ''
  trigger:
  - platform: time
    at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Cambia la mesa y ponte en alto
  mode: single
- id: '1727616826210'
  alias: desk-standup-morning
  description: ''
  trigger:
  - platform: time
    at: '11:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Cambia la mesa y ponte en alto
  mode: single
- id: '1727616966519'
  alias: power-high-automatic-notification
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 5ea25894f6bf324d4ad4c92b7d792f89
    entity_id: sensor.principal_power
    domain: sensor
    above: 3500
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Potencia > 3.5KW vigila los valores
  mode: single
- id: '1727617005120'
  alias: power-too-high
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 5ea25894f6bf324d4ad4c92b7d792f89
    entity_id: sensor.principal_power
    domain: sensor
    above: 5000
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Potencia > 5KW cuidado!!
  mode: single
- id: '1727624091670'
  alias: living-room-air-ok
  description: All good
  trigger:
  - type: value
    platform: device
    device_id: 7f8557c6298a986c45086392c29693dd
    entity_id: sensor.awair_element_74845_score
    domain: sensor
    below: 70
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - type: carbon_dioxide
    platform: device
    device_id: 7f8557c6298a986c45086392c29693dd
    entity_id: sensor.awair_element_74845_carbon_dioxide
    domain: sensor
    above: 800
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: template
    value_template: |
      {% set last_triggered = state_attr(''automation.air_the_living_room'', ''last_triggered'') %}
      {{ last_triggered and (now() - last_triggered).total_seconds() < 3600}}
  action:
  - device_id: 6b65c175185bbcc197739de0d6ff6e91
    domain: mobile_app
    type: notify
    message: Todo OK!
  mode: single
