version: "3.8"
services:
  gluetun:
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - "{{ base_directory }}/gluetun:/gluetun"
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={{ wireguard.PrivateKey }}
      - WIREGUARD_ADDRESSES={{ wireguard.Address }}
      - TZ={{ tz }}
      - SERVER_COUNTRIES=Norway
      - DNS_ADDRESS=192.168.50.1
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8080
      - HTTPPROXY_LOG=on
    networks:
      wgnet:
        ipv4_address: 172.20.0.100
networks:
  main:
    external:
      name: main
  wgnet:
    external:
      name: wgnet