version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    # networks: [main]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ tz }}
      - ADVERTISE_IP=http://192.168.50.100:32400/
      - ALLOWED_NETWORKS=192.168.50.0/24,172.16.0.0/16
    # ports:
    #   - 32400:32400/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
    volumes:
      - "{{ base_directory }}/plex:/config"
      - /data/movies:/movies
      - /data/tv:/tv
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.{{ public_domain }}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls=true"
      #- "traefik.http.services.plex.loadbalancer.server.port=32400"
      #- "traefik.http.services.plex.loadbalancer.server.url=http://192.168.50.100:32400"

#      - "traefik.http.routers.plex.service=plex"
networks:
  main:
    external:
      name: main
  wgnet:
    external:
      name: wgnet