---
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    restart: always
    networks:
      - main
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY={{ secret.tailscale.subnet_auth_key }}
      - TS_ROUTES=192.168.0.0/24,192.168.50.0/24
      - TS_STATE_DIR=/var/lib
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_HOSTNAME=tailscale-subnet-router
      - TS_NO_LOGS_NO_SUPPORT=true
    volumes:
      - "{{ base_directory }}/tailscale:/var/lib"
      - /dev/net/tun:/dev/net/tun