services:
  postgres_db:
    networks: [main]
    container_name: postgres
    image: postgres:latest@sha256:b0a5628e5f6f4ef1feb6a6d5ef2f399f080ad1fa5e333a24659cebfafaca2ac1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: "this-is-a-very-secure-password"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "{{ base_directory }}/postgresql-data:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  main:
    external: true
  wgnet:
    external: true