tls:
  certificates:
    - certFile: /certs/{{ public_domain }}.certificate.pem
      keyFile: /certs/{{ public_domain }}.private.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/{{ public_domain }}.certificate.pem
        keyFile: /certs/{{ public_domain }}.private.pem