## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

# log default is ERROR, but WARN is more helpful
log:
  level: WARN
  # level: INFO
accessLog:
  filePath: "/logs/access.log"

# enable dashboard on 8080 with auth
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: /configuration/
    watch: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ secret.cloudflare.email }}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
        delayBeforeCheck: 10

http:
  services:
    plex:
        loadBalancer:
            passHostHeader: false
            servers:
                - url: http://192.168.50.100:32400 # NOT CONTROLLABLE VIA VARIABLE
# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  mqtt:
    address: :1883
  dns-udp:
    address: ":53/udp"
    udp:
      timeout: 10s
  dns-tcp:
    address: :53
  websecure:
    address: :443