tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: {{ secret.public_domain }}
          sans:
            - "*.{{ secret.public_domain }}"